server:
  port: 8002
spring:
  application:
    name: mcroservice-order  #服务名

#eureka配置
eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机配置
      #defaultZone: http://localhost:7001/eureka
      #集群配置
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    #服务名称修改
    instance-id: order8002
    #访问路径可以显示ip地址
    prefer-ip-address: true